import { DashboardSummary } from '../models/analytics.model';
import { CampusEvent } from '../models/event.model';

export const PREVIEW_EVENTS: CampusEvent[] = [
  {
    id: 'innovation-summit-2026',
    title: 'Innovation Summit 2026',
    shortDescription: 'A campus-wide showcase of product demos, student startups, and AI projects.',
    description:
      'Innovation Summit brings together student founders, faculty mentors, and industry speakers for a full-day experience focused on product thinking, rapid prototyping, and real-world problem solving.',
    category: 'Innovation',
    department: 'Computer Science',
    startDate: '2026-04-12T09:00:00.000Z',
    endDate: '2026-04-12T17:30:00.000Z',
    venue: 'Central Convention Hall',
    mode: 'Hybrid',
    capacity: 320,
    registeredCount: 248,
    organizer: 'Campus Innovation Cell',
    keynote: 'Dr. Mira Nandan, VP of Applied AI',
    tags: ['AI', 'Startups', 'Demo Day'],
    coverGradient: 'linear-gradient(135deg, #0f766e 0%, #134e4a 45%, #f59e0b 100%)',
    agenda: [
      {
        time: '09:00',
        title: 'Opening keynote',
        description: 'A fast-moving look at student innovation and what industry expects next.',
      },
      {
        time: '12:00',
        title: 'Prototype showcase',
        description: 'Teams demo products across sustainability, accessibility, and student life.',
      },
      {
        time: '15:30',
        title: 'Founder roundtable',
        description: 'Campus founders share honest lessons about launching early and learning fast.',
      },
    ],
  },
  {
    id: 'design-jam',
    title: '24-Hour Design Jam',
    shortDescription: 'Cross-disciplinary teams reimagine student services through UX and service design.',
    description:
      'The Design Jam pairs designers, developers, and volunteers from student clubs to redesign parts of campus life. Teams present their work to a panel of mentors after a 24-hour sprint.',
    category: 'Workshop',
    department: 'School of Design',
    startDate: '2026-04-20T13:00:00.000Z',
    endDate: '2026-04-21T13:00:00.000Z',
    venue: 'Maker Lab Studio',
    mode: 'In Person',
    capacity: 120,
    registeredCount: 96,
    organizer: 'Design Guild',
    keynote: 'Lina Sharma, Service Design Director',
    tags: ['UX', 'Research', 'Collaboration'],
    coverGradient: 'linear-gradient(135deg, #1d4ed8 0%, #0f172a 55%, #38bdf8 100%)',
    agenda: [
      {
        time: '13:00',
        title: 'Challenge briefing',
        description: 'Mentors unveil the service-design problem statements and judging criteria.',
      },
      {
        time: '19:00',
        title: 'Midnight check-in',
        description: 'Teams review early concepts, risk areas, and research insights.',
      },
      {
        time: '12:00',
        title: 'Final showcase',
        description: 'Rapid presentations followed by mentor feedback and awards.',
      },
    ],
  },
  {
    id: 'green-campus-forum',
    title: 'Green Campus Forum',
    shortDescription: 'Talks, booths, and student-led initiatives focused on climate action on campus.',
    description:
      'This forum spotlights practical sustainability projects, from waste audits to energy dashboards, and helps students discover volunteer opportunities across campus initiatives.',
    category: 'Community',
    department: 'Environmental Club',
    startDate: '2026-05-02T10:30:00.000Z',
    endDate: '2026-05-02T15:00:00.000Z',
    venue: 'Eco Courtyard',
    mode: 'In Person',
    capacity: 200,
    registeredCount: 134,
    organizer: 'Sustainability Council',
    keynote: 'Aarav Menon, Climate Policy Fellow',
    tags: ['Sustainability', 'Volunteer', 'Community'],
    coverGradient: 'linear-gradient(135deg, #166534 0%, #3f6212 45%, #bef264 100%)',
    agenda: [
      {
        time: '10:30',
        title: 'Campus impact stories',
        description: 'Student teams share measurable wins and failures from the past semester.',
      },
      {
        time: '12:30',
        title: 'Open activity fair',
        description: 'Clubs, labs, and mentors host stations for students to join new initiatives.',
      },
      {
        time: '14:15',
        title: 'Action planning',
        description: 'Participants choose one concrete sustainability action for the next month.',
      },
    ],
  },
  {
    id: 'cyber-defense-lab',
    title: 'Cyber Defense Lab',
    shortDescription: 'Hands-on security challenges for students interested in blue-team operations.',
    description:
      'Cyber Defense Lab is a practical event for students who want to explore threat detection, incident response, and collaborative investigation workflows in a friendly learning environment.',
    category: 'Tech',
    department: 'Information Security',
    startDate: '2026-05-11T11:00:00.000Z',
    endDate: '2026-05-11T18:00:00.000Z',
    venue: 'Digital Security Center',
    mode: 'Virtual',
    capacity: 180,
    registeredCount: 172,
    organizer: 'Cyber Society',
    keynote: 'Neha Patel, Security Operations Lead',
    tags: ['Security', 'CTF', 'Hands-on'],
    coverGradient: 'linear-gradient(135deg, #7c2d12 0%, #431407 55%, #fb923c 100%)',
    agenda: [
      {
        time: '11:00',
        title: 'Threat briefing',
        description: 'A short walkthrough of attack simulation rules and event scoring.',
      },
      {
        time: '14:00',
        title: 'Live investigation',
        description: 'Participants work through telemetry and containment decisions as a group.',
      },
      {
        time: '17:15',
        title: 'Lessons review',
        description: 'Coaches unpack how small signals turned into a full incident narrative.',
      },
    ],
  },
];

export const PREVIEW_DASHBOARD_SUMMARY: DashboardSummary = {
  totalEvents: 12,
  totalRegistrations: 842,
  upcomingEvents: 7,
  avgOccupancy: 78,
  checkInRate: 91,
  completionRate: 88,
  topCategories: [
    { name: 'Tech', count: 286 },
    { name: 'Workshop', count: 214 },
    { name: 'Innovation', count: 182 },
    { name: 'Community', count: 160 },
  ],
  featuredEvents: PREVIEW_EVENTS.slice(0, 3),
  recentActivity: [
    {
      title: 'Registration surge detected',
      detail: 'Cyber Defense Lab crossed 95% occupancy in the last 12 hours.',
      time: '10 minutes ago',
    },
    {
      title: 'Reminder campaign queued',
      detail: 'Upcoming reminder emails are scheduled for Innovation Summit attendees.',
      time: '1 hour ago',
    },
    {
      title: 'Admin review pending',
      detail: 'Two new events are awaiting final approval from the student affairs office.',
      time: '3 hours ago',
    },
  ],
  registrationTrend: [
    { label: '2026-03-11', value: 44 },
    { label: '2026-03-12', value: 58 },
    { label: '2026-03-13', value: 61 },
    { label: '2026-03-14', value: 80 },
    { label: '2026-03-15', value: 74 },
    { label: '2026-03-16', value: 92 },
    { label: '2026-03-17', value: 105 },
  ],
  attendanceTrend: [
    { label: '2026-03-11', value: 18 },
    { label: '2026-03-12', value: 27 },
    { label: '2026-03-13', value: 31 },
    { label: '2026-03-14', value: 42 },
    { label: '2026-03-15', value: 37 },
    { label: '2026-03-16', value: 56 },
    { label: '2026-03-17', value: 64 },
  ],
  modeBreakdown: [
    { label: 'In Person', value: 5 },
    { label: 'Hybrid', value: 4 },
    { label: 'Virtual', value: 3 },
  ],
};
